### ISSUE TITLE
BW 1.2

### ISSUE THREAD

**Issue by clayallsopp** [rubymotion/BubbleWrap#207]
Hey guys, thought I'd get the ball rolling on the next release, which I guess will be 1.2?

Looks like it will include:
- [x] `UIBarButtonItem` wrapper (#202)
- ~~BW::Alert (#201)~~
- [x] BW::Font (#206)
- [x] BW::Reactor::Eventable#off (#205)
- [x] BW::HTTP#cookies (#204)
- [x] BW::Constants.get (#203)
- [x] BW::Location.get_once (#197)
- [x] App#environment (#191)
- [x] BW::HTTP `:follow_urls` option (#192)
- [x] BW::Reactor `:common_modes` option (#190)
- [x] BW::HTTP `:no_redirect` option (#187)

@mneorr @jamesotron I noticed there's not a tag for 1.1.5 in https://github.com/rubymotion/BubbleWrap/tags? something not get synced?
